#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$APP_DIR/.env"
ENV_EXAMPLE="$APP_DIR/.env.example"
COMPOSE_FILE="$APP_DIR/docker-compose.yml"
COMPOSE_OVERRIDE="$APP_DIR/docker-compose.vm.override.yml"
NGINX_SITE="/etc/nginx/sites-available/arlo"
NGINX_ENABLED="/etc/nginx/sites-enabled/arlo"
COMPOSE_SERVICES=(mysql backend frontend rtms)

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run this script as root: sudo $0"
  exit 1
fi

if [[ ! -f "$ENV_EXAMPLE" ]]; then
  echo "Missing $ENV_EXAMPLE"
  exit 1
fi

if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "Missing $COMPOSE_FILE"
  exit 1
fi

if ! command -v apt-get >/dev/null 2>&1; then
  echo "This setup script currently supports Debian/Ubuntu systems with apt."
  exit 1
fi

if [[ ! -f /etc/os-release ]]; then
  echo "Cannot determine OS distribution."
  exit 1
fi

# shellcheck disable=SC1091
source /etc/os-release
if [[ "${ID:-}" != "ubuntu" && "${ID:-}" != "debian" ]]; then
  echo "This draft script currently supports Debian/Ubuntu only."
  exit 1
fi

APP_OWNER="${SUDO_USER:-$(logname 2>/dev/null || true)}"
if [[ -z "${APP_OWNER}" || "${APP_OWNER}" == "root" ]]; then
  APP_OWNER="$(stat -c '%U' "$APP_DIR")"
fi
APP_GROUP="$(id -gn "$APP_OWNER")"

prompt_required() {
  local prompt="$1"
  local value=""
  while [[ -z "$value" ]]; do
    read -r -p "$prompt: " value
  done
  printf '%s' "$value"
}

prompt_default() {
  local prompt="$1"
  local default_value="$2"
  local value=""
  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt [$default_value]: " value
  else
    read -r -p "$prompt: " value
  fi
  if [[ -z "$value" ]]; then
    value="$default_value"
  fi
  printf '%s' "$value"
}

prompt_secret() {
  local prompt="$1"
  local value=""
  while [[ -z "$value" ]]; do
    read -r -s -p "$prompt: " value
    printf '\n'
  done
  printf '%s' "$value"
}

generate_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi

  od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
}

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    echo "Docker is already installed."
    return
  fi

  echo "Installing Docker..."
  apt-get update
  apt-get install -y ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL "https://download.docker.com/linux/${ID}/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  printf '%s\n' \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list

  apt-get update
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
}

install_proxy_packages() {
  echo "Installing nginx and certbot..."
  apt-get update
  apt-get install -y nginx certbot python3-certbot-nginx
  systemctl enable --now nginx
}

disable_apache_if_needed() {
  if systemctl list-unit-files apache2.service >/dev/null 2>&1; then
    if systemctl is-active --quiet apache2; then
      echo "Stopping apache2 so nginx can own ports 80/443..."
      systemctl stop apache2
    fi
    if systemctl is-enabled --quiet apache2; then
      systemctl disable apache2
    fi
  fi
}

write_env_file() {
  local fqdn="$1"
  local public_url="https://${fqdn}"
  local client_id="$2"
  local client_secret="$3"
  local app_id="$4"
  local openrouter_api_key="$5"
  local default_model="$6"
  local fallback_model="$7"
  local session_secret="$8"
  local encryption_key="$9"
  local database_password="${10}"
  local mysql_root_password="${11}"
  local ai_enabled="false"

  if [[ -n "$openrouter_api_key" ]]; then
    ai_enabled="true"
  fi

  if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by deploy/selfhost/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
ZOOM_CLIENT_ID=${client_id}
ZOOM_CLIENT_SECRET=${client_secret}
ZOOM_APP_ID=${app_id}
ZOOM_HOST=zoom.us

PUBLIC_URL=${public_url}
ZOOM_APP_REDIRECT_URI=\${PUBLIC_URL}/api/auth/callback

MYSQL_USER=arlo
MYSQL_PASSWORD=${database_password}
MYSQL_ROOT_PASSWORD=${mysql_root_password}
DATABASE_URL=mysql://arlo:${database_password}@mysql:3306/meeting_assistant

SESSION_SECRET=${session_secret}
REDIS_ENCRYPTION_KEY=${encryption_key}

REDIS_URL=

OPENROUTER_API_KEY=${openrouter_api_key}
DEFAULT_MODEL=${default_model}
FALLBACK_MODEL=${fallback_model}
FALLBACK_MODELS=${fallback_model},nvidia/nemotron-3-ultra-550b-a55b:free

AI_ENABLED=${ai_enabled}
EXTRACTION_ENABLED=false
PUBLIC_LINKS_ENABLED=false
DISABLE_MEETING_PERSISTENCE=false

PORT=3000
NODE_ENV=production
FRONTEND_URL=${public_url}
FRONTEND_UPSTREAM_URL=http://frontend:3000

RTMS_WEBHOOK_SECRET=
RTMS_PORT=3002

LOG_LEVEL=info
CORS_ORIGINS=${public_url},http://localhost:3001

VTT_STORAGE_PATH=./storage/vtt
S3_BUCKET=
S3_REGION=
S3_ACCESS_KEY=
S3_SECRET_KEY=
EOF

  chown "${APP_OWNER}:${APP_GROUP}" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

write_compose_override() {
  cat > "$COMPOSE_OVERRIDE" <<'EOF'
services:
  backend:
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ""
      NODE_ENV: production
      FRONTEND_URL: ${PUBLIC_URL}
      FRONTEND_UPSTREAM_URL: http://frontend:3000
      CORS_ORIGINS: ${PUBLIC_URL},http://localhost:3001
    command: sh -c "npx prisma generate && npx prisma db push && npm run start"

  frontend:
    env_file:
      - .env
    environment:
      REACT_APP_API_URL: ${PUBLIC_URL}
      REACT_APP_WS_URL: ${PUBLIC_URL}
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    command: npm start

  rtms:
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BACKEND_URL: http://backend:3000
      NODE_ENV: production
    command: npm start
EOF
}

start_stack() {
  echo "Starting Arlo services with Docker Compose..."
  cd "$APP_DIR"
  docker compose \
    --env-file "$ENV_FILE" \
    -f "$COMPOSE_FILE" \
    -f "$COMPOSE_OVERRIDE" \
    up -d --build "${COMPOSE_SERVICES[@]}"
}

write_nginx_site() {
  local fqdn="$1"

  cat > "$NGINX_SITE" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${fqdn};

    client_max_body_size 10m;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF

  ln -sfn "$NGINX_SITE" "$NGINX_ENABLED"
  rm -f /etc/nginx/sites-enabled/default
  nginx -t
  systemctl reload nginx
}

maybe_issue_cert() {
  local fqdn="$1"
  local email="$2"

  if [[ -z "$email" ]]; then
    echo "Skipping Let's Encrypt. Re-run later with an email to enable HTTPS automatically."
    return
  fi

  echo "Requesting Let's Encrypt certificate for ${fqdn}..."
  certbot --nginx --non-interactive --agree-tos -m "$email" -d "$fqdn" --redirect
  systemctl reload nginx
}

wait_for_health() {
  echo "Waiting for backend and RTMS health checks..."
  for _ in $(seq 1 90); do
    if curl -fsS http://127.0.0.1:3000/health >/dev/null 2>&1 && \
       curl -fsS http://127.0.0.1:3002/health >/dev/null 2>&1; then
      echo "Backend and RTMS are healthy."
      return
    fi
    sleep 2
  done

  echo "Services did not become healthy in time."
  cd "$APP_DIR"
  docker compose \
    --env-file "$ENV_FILE" \
    -f "$COMPOSE_FILE" \
    -f "$COMPOSE_OVERRIDE" \
    logs --tail=100 backend frontend rtms mysql || true
  exit 1
}

echo "Arlo VM setup (draft)"
echo "This script installs Docker/nginx, prompts for secrets, writes .env, and starts Arlo with Docker Compose."
echo

echo "Installing system dependencies..."
install_docker
install_proxy_packages
disable_apache_if_needed

if ! id -nG "$APP_OWNER" | grep -qw docker; then
  usermod -aG docker "$APP_OWNER"
fi

FQDN="$(prompt_required "What FQDN should Arlo use (example: arlo.example.com)")"
LETSENCRYPT_EMAIL="$(prompt_default "Email for Let's Encrypt certificates (leave blank to skip HTTPS for now)" "")"
ZOOM_CLIENT_ID="$(prompt_required "Zoom Client ID")"
ZOOM_CLIENT_SECRET="$(prompt_secret "Zoom Client Secret")"
ZOOM_APP_ID="$(prompt_default "Zoom App ID (optional)" "")"
OPENROUTER_API_KEY="$(prompt_default "OpenRouter API key (optional)" "")"
DEFAULT_MODEL="$(prompt_default "Default OpenRouter model" "openai/gpt-oss-120b:free")"
FALLBACK_MODEL="$(prompt_default "Fallback OpenRouter model" "google/gemma-4-31b-it:free")"
SESSION_SECRET="$(generate_hex 32)"
REDIS_ENCRYPTION_KEY="$(generate_hex 16)"
DATABASE_PASSWORD="$(generate_hex 24)"
MYSQL_ROOT_PASSWORD="$(generate_hex 32)"

echo "Writing $ENV_FILE..."
write_env_file \
  "$FQDN" \
  "$ZOOM_CLIENT_ID" \
  "$ZOOM_CLIENT_SECRET" \
  "$ZOOM_APP_ID" \
  "$OPENROUTER_API_KEY" \
  "$DEFAULT_MODEL" \
  "$FALLBACK_MODEL" \
  "$SESSION_SECRET" \
  "$REDIS_ENCRYPTION_KEY" \
  "$DATABASE_PASSWORD" \
  "$MYSQL_ROOT_PASSWORD"

echo "Writing $COMPOSE_OVERRIDE..."
write_compose_override

start_stack
wait_for_health

echo "Configuring nginx for ${FQDN}..."
write_nginx_site "$FQDN"
maybe_issue_cert "$FQDN" "$LETSENCRYPT_EMAIL"

cat <<EOF

Setup complete.

App URL: https://${FQDN}
OAuth callback: https://${FQDN}/api/auth/callback
RTMS webhook: https://${FQDN}/api/rtms/webhook

Useful commands:
  cd ${APP_DIR}
  docker compose -f docker-compose.yml -f docker-compose.vm.override.yml ps
  docker compose -f docker-compose.yml -f docker-compose.vm.override.yml logs -f backend
  docker compose -f docker-compose.yml -f docker-compose.vm.override.yml logs -f rtms

Zoom Marketplace values:
  Home URL: https://${FQDN}/
  OAuth Redirect URL: https://${FQDN}/api/auth/callback
  Event notification endpoint: https://${FQDN}/api/rtms/webhook
  Domain Allow List: ${FQDN}

If Docker group access was just added for ${APP_OWNER}, that user may need to
log out and back in before plain 'docker' commands work without sudo.
EOF
